language: node_js
node_js: '12'
branches:
  only:
    - master

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local_dir: public
  on:
    branch: master